@endpoint = http://localhost:8080/api/todos

### Show all
GET {{endpoint}}

### Search by id (no todos found)
GET {{endpoint}}/396ebe2c-c230-40a0-80ec-f0cb40915e53

### Search by id (invalid)
GET {{endpoint}}/396ebe2c-c230- 40a0-80ec-f0cb40915e53

### Search by id (blows up)
GET {{endpoint}}/bla

### Search by id (the one that works)
GET {{endpoint}}/017d2d03-febf-464a-b92c-01a17898f551

### Delete all
DELETE {{endpoint}}

### Delete (no todos found)
DELETE {{endpoint}}/396ebe2c-c230-40a0-80ec-f0cb40915e53

### Delete (invalid)
DELETE {{endpoint}}/396ebe2c-c230- 40a0-80ec-f0cb40915e53

### Delete (blows up)
DELETE {{endpoint}}/bla

### Delete (the one that works)
DELETE {{endpoint}}/396ebe2c-c230-40a0-80ec-f0cb40915e52
